package com.forma.app.domain.model

/**
 * Encapsulates the comprehensive output generated by Forma's Gemini AI engine.
 */
data class AiGenerationResult(
    val title: String,
    val summary: String,
    val tasks: List<TimelineItem>,
    val suggestedHabits: List<Habit>,
    val tips: List<String>
)
